version: '3.9'

services:
  web:
    container_name: appquilar-web-dev
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      VITE_API_BASE_URL: "http://localhost:8000"
      VITE_USE_MOCK_DATA: "false"
    ports:
      - "8080:8080"
    networks:
      - appquilar

networks:
  appquilar:
    external: true
