version: '3.9'

services:
  web:
    container_name: appquilar-web-prod
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    networks:
      - appquilar

networks:
  appquilar:
    external: true
